# Generated by Django 5.1.1 on 2024-09-27 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calzados',
            fields=[
                ('CalzadoId', models.AutoField(primary_key=True, serialize=False)),
                ('CalzadoName', models.CharField(max_length=500)),
                ('CalzadoCodigoBarras', models.CharField(max_length=500)),
                ('CalzadoProveedor', models.CharField(max_length=500)),
                ('CalzadoInversionista', models.CharField(max_length=500)),
                ('CalzadoCantidad', models.IntegerField()),
                ('CalzadoPrecioCompra', models.FloatField()),
                ('CalzadoPrecioVenta', models.FloatField()),
                ('fechaCreate', models.DateTimeField(auto_now_add=True)),
                ('fechaUpdate', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(max_length=500)),
            ],
        ),
    ]
